# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6144M -XX:+UseG1GC
kotlin.native.jvmargs=-Xmx6144M

# Gradle
org.gradle.jvmargs=-Xmx6144M -Dfile.encoding=UTF-8 -XX:+UseG1GC
org.gradle.configuration-cache=true
org.gradle.caching=true

# Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# MOKO Resources
moko.resources.BUILT_PRODUCTS_DIR=${env.BUILT_PRODUCTS_DIR}
moko.resources.CONTENTS_FOLDER_PATH=${env.CONTENTS_FOLDER_PATH}
moko.resources.UNLOCALIZED_RESOURCES_FOLDER_PATH=${env.UNLOCALIZED_RESOURCES_FOLDER_PATH}
moko.resources.disableStaticFrameworkWarning=true

# Suppress dependency constraints warning
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
