package com.dnfapps.arrmatey.bazarr.api.model

import kotlinx.serialization.Serializable

@Serializable
data class BazarrSystem(
    val addic7ed: Addic7edSettings,
    val analytics: AnalyticsSettings,
    val anidb: AniDBSettings,
    val animetosho: AnimeToshoSettings,
    val anticaptcha: AntiCaptchaSettings,
    val assrt: AssrtSettings,
    val auth: AuthSettings,
    val avistaz: AvistazSettings,
    val backup: BackupSettings,
    val betaseries: BetaSeriesSettings,
    val cinemaz: CinemazSettings,
    val cors: CorsSettings,
    val deathbycaptcha: DeathByCaptchaSettings,
    val embeddedsubtitles: EmbeddedSubtitlesSettings,
    val general: GeneralSettings,
    val hdbits: HDBitsSettings,
    val jimaku: JimakuSettings,
    val karagarga: KaragargaSettings,
    val ktuvit: KtuvitSettings,
    val legendasdivx: LegendasDivxSettings,
    val legendasnet: LegendasNetSettings,
    val legendastv: LegendasTVSettings,
    val log: LogSettings,
    val movie_scores: MovieScoresSettings,
    val napiprojekt: NapiProjektSettings,
    val napisy24: Napisy24Settings,
    val notifications: NotificationsSettings,
    val opensubtitles: OpenSubtitlesSettings,
    val opensubtitlescom: OpenSubtitlesComSettings,
    val plex: PlexSettings,
    val podnapisi: PodnapisiSettings,
    val postgresql: PostgreSqlSettings,
    val proxy: ProxySettings,
    val radarr: RadarrSettings,
    val series_scores: SeriesScoresSettings,
    val sonarr: SonarrSettings,
    val subdl: SubDlSettings,
    val subf2m: SubF2MSettings,
    val subscene: SubsceneSettings,
    val subsource: SubSourceSettings,
    val subsync: SubsyncSettings,
    val subx: SubxSettings,
    val titlovi: TitloviSettings,
    val titulky: TitulkySettings,
    val translator: TranslatorSettings,
    val turkcealtyaziorg: TurkceAltyaziOrgSettings,
    val whisperai: WhisperAiSettings,
    val xsubs: XSubsSettings,
)
