package com.dnfapps.arrmatey.tracearr.api.model

import kotlinx.serialization.Serializable

@Serializable
data class TracearrStreamSession(
    val id: String,
    val serverId: String,
    val serverUserId: String? = null,
    val sessionKey: String? = null,
    val state: String? = null,
    val mediaType: TracearrMediaType? = null,
    val mediaTitle: String? = null,
    val grandparentTitle: String? = null,
    val seasonNumber: Int? = null,
    val episodeNumber: Int? = null,
    val year: Int? = null,
    val thumbPath: String? = null,
    val ratingKey: String? = null,
    val serverVersionKey: String? = null,
    val parentRatingKey: String? = null,
    val grandparentRatingKey: String? = null,
    val mediaId: String? = null,
    val showMediaId: String? = null,
    val imdbId: String? = null,
    val tmdbId: Long? = null,
    val tvdbId: Long? = null,
    val externalSessionId: String? = null,
    val startedAt: String? = null,
    val stoppedAt: String? = null,
    val durationMs: Long? = null,
    val totalDurationMs: Long? = null,
    val progressMs: Long? = null,
    val lastPausedAt: String? = null,
    val pausedDurationMs: Long? = null,
    val referenceId: String? = null,
    val watched: Boolean? = null,
    val ipAddress: String? = null,
    val geoCity: String? = null,
    val geoRegion: String? = null,
    val geoCountry: String? = null,
    val geoContinent: String? = null,
    val geoPostal: String? = null,
    val geoLat: Double? = null,
    val geoLon: Double? = null,
    val geoAsnNumber: String? = null,
    val geoAsnOrganization: String? = null,
    val playerName: String? = null,
    val deviceId: String? = null,
    val product: String? = null,
    val device: String? = null,
    val platform: String? = null,
    val quality: String? = null,
    val isTranscode: Boolean? = null,
    val videoDecision: TracearrStreamDecision? = null,
    val audioDecision: TracearrStreamDecision? = null,
    val bitrate: Int? = null,
    val sourceVideoCodec: String? = null,
    val sourceAudioCodec: String? = null,
    val sourceAudioChannels: Int? = null,
    val sourceVideoWidth: Int? = null,
    val sourceVideoHeight: Int? = null,
    val sourceVideoDetails: TracearrSourceVideoDetails? = null,
    val sourceAudioDetails: TracearrSourceAudioDetails? = null,
    val streamVideoCodec: String? = null,
    val streamAudioCodec: String? = null,
    val streamVideoDetails: TracearrStreamVideoDetails? = null,
    val streamAudioDetails: TracearrStreamAudioDetails? = null,
    val transcodeInfo: TracearrTranscodeInfo? = null,
    val subtitleInfo: TracearrSubtitleInfo? = null,
    val channelTitle: String? = null,
    val channelIdentifier: String? = null,
    val channelThumb: String? = null,
    val artistName: String? = null,
    val albumName: String? = null,
    val trackNumber: Int? = null,
    val discNumber: Int? = null,
    val user: TracearrUser? = null,
    val server: TracearrServer? = null,
    val canTerminate: Boolean? = null,
    val showTitle: String? = null,
    val audioChannelsDisplay: String? = null,
    val genres: List<String> = emptyList(),
    val libraryId: String? = null,
    val posterUrl: String? = null,
    val player: String? = null,
    val resolution: String? = null,
    val sourceAudioCodecDisplay: String? = null,
    val sourceVideoCodecDisplay: String? = null,
    val streamAudioCodecDisplay: String? = null,
    val streamVideoCodecDisplay: String? = null,
)
